// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSP-biVPffzaeTr70nemVDyPaMS6yYUGE',
    appId: '1:906341423350:web:9e20bc54fd161a271bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    authDomain: 'tvsapp-ac523.firebaseapp.com',
    storageBucket: 'tvsapp-ac523.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIzls4mKC9qKhl9xR-NKFFprmiruDEQI',
    appId: '1:906341423350:android:187cfb35749c4c551bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    storageBucket: 'tvsapp-ac523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvyUXFzFuTZhM-xpZePbLy4SE4UGp8DB8',
    appId: '1:906341423350:ios:af6e68e7bfaad51a1bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    storageBucket: 'tvsapp-ac523.appspot.com',
    iosBundleId: 'com.example.tvsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvyUXFzFuTZhM-xpZePbLy4SE4UGp8DB8',
    appId: '1:906341423350:ios:043913eae095ded81bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    storageBucket: 'tvsapp-ac523.appspot.com',
    iosBundleId: 'com.example.tvsApp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSP-biVPffzaeTr70nemVDyPaMS6yYUGE',
    appId: '1:906341423350:web:34bfc4d42e0d05701bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    authDomain: 'tvsapp-ac523.firebaseapp.com',
    storageBucket: 'tvsapp-ac523.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCSP-biVPffzaeTr70nemVDyPaMS6yYUGE',
    appId: '1:906341423350:web:b82ec207ae00ff981bf4d7',
    messagingSenderId: '906341423350',
    projectId: 'tvsapp-ac523',
    authDomain: 'tvsapp-ac523.firebaseapp.com',
    storageBucket: 'tvsapp-ac523.appspot.com',
  );
}
